import { chromium, devices } from '@playwright/test'
const SHOT = process.env.SHOT
const browser = await chromium.launch()
const ctx = await browser.newContext({ ...devices['iPhone 13'] })
const page = await ctx.newPage()
const errors = []
page.on('pageerror', (e) => errors.push('PAGEERROR ' + e.message))
page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()) })
await page.goto(process.env.APP_URL ?? 'http://localhost:5173/')
await page.getByRole('button', { name: '⚙ 設定' }).tap()
await page.getByText('モック JEV').tap()
await page.getByRole('button', { name: '🏁 レース' }).tap()
await page.getByRole('button', { name: '記事から' }).tap()
await page.getByPlaceholder('座標を持つ記事名').fill('東京タワー')
await page.locator('.suggest li').first().tap()
await page.locator('strong', { hasText: '周辺' }).waitFor({ timeout: 20000 })
// Human + JEV 1体
const picks = page.locator('.runner-picks input[type=checkbox]')
for (let i = 0; i < await picks.count(); i++) { if (await picks.nth(i).isChecked()) await picks.nth(i).tap() }
await page.locator('.runner-picks label', { hasText: 'あなた' }).locator('input').tap()
await page.locator('.runner-picks label', { hasText: 'ガンガン' }).locator('input').tap()
await page.getByRole('button', { name: '全員同一' }).tap()
await page.getByRole('button', { name: '🎲 スタート生成' }).tap()
await page.locator('ul.small li').nth(1).waitFor({ timeout: 90000 })
await page.screenshot({ path: SHOT + '/m-setup.png', fullPage: true })
await page.getByRole('button', { name: '🏁 レース開始' }).tap()
await page.locator('.reader-body a.legal').first().waitFor({ timeout: 30000 })
await page.screenshot({ path: SHOT + '/m-reader.png' })
const n = await page.locator('.reader-body a.legal').count()
const dead = await page.locator('.reader-body a.dead').count()
console.log('legal anchors', n, 'dead anchors', dead, 'head:', await page.locator('.reader-head').innerText())
const backDisabled = await page.getByRole('button', { name: /BACK/ }).isDisabled()
console.log('BACK disabled at start:', backDisabled)
const target = await page.locator('.reader-body a.legal').nth(3).getAttribute('data-move')
await page.locator('.reader-body a.legal').nth(3).tap()
await page.screenshot({ path: SHOT + '/m-select.png' })
await page.getByRole('button', { name: '決定' }).tap()
await page.getByText('ターン 1 /').waitFor({ timeout: 60000 })
await page.getByRole('button', { name: '実況' }).tap()
console.log('log:', (await page.locator('.log').innerText()).slice(0, 300))
console.log('expected move to', target)
await page.getByRole('button', { name: '地図' }).tap()
await page.waitForTimeout(1500)
await page.screenshot({ path: SHOT + '/m-map.png' })
// 2ターン目: BACK を使う
await page.getByRole('button', { name: 'Reader' }).tap()
await page.getByRole('button', { name: /BACK/ }).tap()
await page.getByRole('button', { name: '決定' }).tap()
await page.getByText('ターン 2 /').waitFor({ timeout: 60000 })
await page.getByRole('button', { name: 'Runner', exact: true }).tap()
console.log('board:', (await page.locator('.split-side').innerText()).slice(0, 400))
console.log('errors:', errors)
await browser.close()
